---
  - name: change sysctl settings
    sysctl:
      name: '{{ item.key }}'
      value: '{{ item.value }}'
      sysctl_set: yes
      state: present
      reload: yes
    with_dict: '{{ sysctl_settings }}'
