---
- name: Add ansible user
  user:
    name: "{{ deployment_user }}"
    shell: /bin/bash
    create_home: yes
    state: present
- name: add ssh key
  authorized_key:
    user: "{{ deployment_user }}"
    key: "{{ deployment_key }}"
- name: install sudo
  apt:
    name: sudo
    state: present
- name: add ansible user to sudoers w/o password
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: "^{{ deployment_user }} ALL="
    line: "{{ deployment_user }} ALL=(ALL) NOPASSWD:ALL"
    validate: "visudo -cf %s"
