---
- name: Install automatic updates
  apt:
    pkg:
    - unattended-upgrades
    - apt-listchanges
- name: Configure automatic updates
  copy:
    src: '{{ item }}'
    dest: /etc/apt/apt.conf.d/
  with_items:
    - 20auto-upgrades
    - 50unattended-upgrades
- name: Install cli tools
  apt:
    pkg:
    - tmux
    - ncdu
    - python3
    - vifm
    - vim-nox
- name: Create wheel group
  group:
    name: wheel
    state: present
  become: yes
- name: Enable pam wheel
  lineinfile:
    path: /etc/pam.d/su
    regexp: '^#auth       required pam_wheel.so'
    line: 'auth       required pam_wheel.so'
  become: yes
- name: Configuring vim
  copy:
    src: vimrc
    dest: /etc/vimrc
    mode: '0644'
- name: Set up inital users
  user:
    name: '{{ item.key }}'
    shell: '/bin/bash'
    groups: wheel
    create_home: True
    state: present
  with_dict: '{{ additional_users }}'
  become: yes
- name: Set up ssh keys
  authorized_key:
    user: '{{ item.key }}'
    key: '{{ item.value }}'
  with_dict: '{{ additional_users }}'
  become: yes
