---
- name: Install automatic updates
  apt:
    pkg:
    - unattended-upgrades
    - apt-listchanges
- name: Configure automatic updates
  copy:
    src: "{{ item }}"
    dest: /etc/apt/apt.conf.d/
  with_items:
    - 20auto-upgrades
    - 50unattended-upgrades
- name: Install cli tools
  apt:
    pkg:
    - tmux
    - ncdu
    - python3
    - vifm
    - vim-nox
- name: Configuring vim
  copy:
    src: vimrc
    dest: /etc/vimrc
    mode: '0644'
- name: Set up inital users
  user:
    name: '{{ item.key }}'
    shell: '/bin/bash'
    create_home: True
    present: True
  with_dict: '{{ initial_users }}'
- name: Set up ssh keys
  authorized_key:
    user: '{{ item.key }}'
    key: '{{ item.value }}'
    state: present
  with_dict: '{{ initial_users }}'

