---
- name: Debian update
  apt:
    update_cache: yes
    upgrade: dist
- name: Install
  apt:
    name: vim-nox
    state: present
- name: configuring vim
  copy:
    src: vimrc
    dest: /etc/vimrc
    mode: '0644'
- name: Install cli tools
  apt:
    pkg:
    - tmux
    - ncdu
    - python3
    - vifm
- name: Reboot on panic
  sysctl:
    name: kernel.panic
    value: '3'
    state: present
    reload: yes
